const express = require("express")
const router = express.Router()
const authController = require("../controllers/auth")

router.post("/logout",authController.Logout)
router.get("/login",authController.renderLogin)
router.post("/login",authController.postLogin)
router.get("/register",authController.renderRegister)
router.post("/register",authController.register)
router.get("/reset_password",authController.renderReset)
router.post('/reset_password',authController.resetLink)
router.get("/feedBack",authController.feedBack)
router.get("/reset_password/:token",authController.getResetForm)
router.post("/reset_password/:token",authController.resetForm)
module.exports = router